#!/usr/bin/env sh
# NullReport one-line installer.
#
#   curl -fsSL https://raw.githubusercontent.com/izzy0101010101/nullreport-install/main/install.sh | sh
#
# Optional overrides (prefix the command):
#   TIER=pro LICENSE_KEY=NR-PRO-xxxxx  curl -fsSL …/install.sh | sh
#   NULLREPORT_DIR=/opt/nullreport     curl -fsSL …/install.sh | sh
#   FRONTEND_PORT=8080                 curl -fsSL …/install.sh | sh
#   WITH_OLLAMA=1                      curl -fsSL …/install.sh | sh   # bundle local AI
#
# Idempotent: re-running reuses the existing .env so your secrets (and the
# data they encrypt) are never rotated out from under you.
set -eu

REPO_RAW="https://raw.githubusercontent.com/izzy0101010101/nullreport-install/main"
DIR="${NULLREPORT_DIR:-nullreport}"
TIER="${TIER:-free}"
LICENSE_KEY="${LICENSE_KEY:-}"
PORT="${FRONTEND_PORT:-3000}"
WITH_OLLAMA="${WITH_OLLAMA:-}"

say() { printf '\033[1;35m▸\033[0m %s\n' "$1"; }
die() { printf '\033[1;31m✗ %s\033[0m\n' "$1" >&2; exit 1; }

# 1. Preflight ---------------------------------------------------------------
command -v docker >/dev/null 2>&1 || die "Docker is not installed — see https://docs.docker.com/get-docker/"
docker compose version >/dev/null 2>&1 || die "Docker Compose v2 required (the 'docker compose' plugin)."
command -v curl >/dev/null 2>&1 || die "curl is required."

# 2. Workspace ---------------------------------------------------------------
mkdir -p "$DIR"
cd "$DIR"

# 3. Compose file ------------------------------------------------------------
say "Downloading docker-compose.prod.yml…"
curl -fsSL "$REPO_RAW/docker-compose.prod.yml" -o docker-compose.yml || die "Could not download the compose file."

# Optional: bundle Ollama for local AI. Ask if interactive and not preset.
if [ -z "$WITH_OLLAMA" ] && [ -r /dev/tty ]; then
  printf '\033[1;35m▸\033[0m Set up local AI with Ollama (runs AI on this machine, ~heavy)? [y/N] '
  read ans </dev/tty || ans=""
  case "$ans" in [Yy]*) WITH_OLLAMA=1 ;; esac
fi
COMPOSE_FILES="docker-compose.yml"
if [ "$WITH_OLLAMA" = "1" ]; then
  say "Including bundled Ollama…"
  curl -fsSL "$REPO_RAW/docker-compose.ollama.yml" -o docker-compose.ollama.yml || die "Could not download the Ollama override."
  COMPOSE_FILES="docker-compose.yml:docker-compose.ollama.yml"
fi

# 4. Secrets / .env — generate ONCE; never rotate (would orphan encrypted data)
gen() { openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'; }

if [ -f .env ]; then
  say "Reusing existing .env (secrets preserved)."
  # Reflect the Ollama choice on re-run (docker compose reads COMPOSE_FILE from .env).
  if [ "$WITH_OLLAMA" = "1" ] && ! grep -q '^COMPOSE_FILE=' .env; then
    printf 'COMPOSE_FILE=%s\n' "$COMPOSE_FILES" >> .env
  fi
else
  say "Generating secrets…"
  umask 077
  cat > .env <<EOF
# Generated by install.sh. KEEP THIS FILE — rotating these after first run
# makes already-stored data unreadable.
JWT_SECRET=$(gen)
ENCRYPTION_KEY=$(gen)
POSTGRES_PASSWORD=$(gen)
TIER=$TIER
LICENSE_KEY=$LICENSE_KEY
FRONTEND_PORT=$PORT
COMPOSE_FILE=$COMPOSE_FILES
EOF
fi

# 5. Launch ------------------------------------------------------------------
say "Pulling images (tier: $TIER)…"
docker compose pull
say "Starting…"
docker compose up -d

printf '\n'
say "NullReport is starting at http://localhost:$PORT"
say "First boot runs DB setup — give it ~20s, then refresh."
if [ "$WITH_OLLAMA" = "1" ]; then
  say "Local AI is bundled — open Settings → AI → Ollama and click a model to download it."
fi
say "Manage it from the '$DIR' folder: docker compose ps | logs -f | down"
